[project]
name = "matmul.mojo"
version = "0.1.0"
description = "Add a short description here"
authors = ["Ethan Wu <yichengdwu@outlook.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
platforms = ["linux-64"]

[tasks]

[dependencies]
numpy = ">=2.0.1,<2.1"
matplotlib = ">=3.9.1,<3.10"
